on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

name: Lint

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: |
          forge --version
          forge build --sizes
          
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g solhint
      - run: solhint './src/**/*.sol'
