name: Run Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-slither:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
            node-version : 18.15
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install node packages
        run: yarn install
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install slither-analyzer==0.8.3

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          node-version: 18.15
          slither-config: ./slither.config.json
          fail-on: medium
          sarif: results.sarif
          slither-version: 0.9.0
          target: ./
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

      - name: Create/update checklist as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body = `${{ steps.slither.outputs.stdout }}`
            await script({ github, context, header, body })
